version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=simplebank
    ports:
      - "5432:5432"
    volumes:
      - "data-volume:/var/lib/postgresql/data"
  redis:
    image: redis:latest
  api: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9091:9091"
    environment:
      - DB_SOURCE=postgresql://root:root@postgres:5432/simplebank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", /app/start.sh ]
    command: [ "/app/main" ]
volumes:
  data-volume: